function throw_exception() {
    trivial_plugin.throw_exception();
}

throw_exception()

print("OK")
